const PHASES = {
  LOBBY: 'LOBBY',
  PROMPT_WRITE: 'PROMPT_WRITE',
  MATCHUP_VOTE: 'MATCHUP_VOTE',
  MATCHUP_RESULTS: 'MATCHUP_RESULTS',
  SET_SCORES: 'SET_SCORES',
  FINAL_SCORES: 'FINAL_SCORES'
};

const WORD_LIMITS = [15, 7, 3, 1];
const ROUND_TIMERS = [30, 20, 15, 10];
const VOTE_TIMER = 10;
const ROUNDS_PER_SET = 4;
const SETS_PER_GAME = 3;
const RESULTS_PAUSE = 3000;
const SET_SCORES_PAUSE = 6000;
const MATCHUP_RESULTS_PAUSE = 4000;
const TRIPLE_THRESHOLD = 9;

const SCORING = {
  PAIR_WIN: 500,
  PAIR_SHUTOUT: 750,
  PAIR_TIE: 250,
  TRIPLE_FIRST: 500,
  TRIPLE_SECOND: 200,
  TRIPLE_THIRD: 0,
  TRIPLE_SHUTOUT: 750,
  FINAL_ROUND_MULTIPLIER: 2
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    PHASES, WORD_LIMITS, ROUND_TIMERS, VOTE_TIMER,
    ROUNDS_PER_SET, SETS_PER_GAME, RESULTS_PAUSE,
    SET_SCORES_PAUSE, MATCHUP_RESULTS_PAUSE,
    TRIPLE_THRESHOLD, SCORING
  };
}
